include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_type_to_string
    - comment_references
    - join_return_with_assignment
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_single_quotes
    - unawaited_futures
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_named_constants
    - require_trailing_commas
    - prefer_constructors_over_static_methods
    - prefer_final_locals
    - prefer_final_fields
    - avoid_setters_without_getters
    - sort_unnamed_constructors_first
    - use_enums
    - sort_pub_dependencies
