name: dart_pusher_channels
description: Dart implementation of client of Pusher Channels protocol, instrument to work with real-time applications. 
version: 1.3.0

environment:
  sdk: ^3.0.0

repository: https://github.com/kerimamansaryyev/dart_pusher_channels

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  http: ^1.0.0
  meta: ^1.8.0
  pinenacl: ^0.6.0
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
